import type { PrismaClient } from "@prisma/client"

export async function seedVenues(prisma: PrismaClient): Promise<number> {
  // Check if venues already exist
  const existingCount = await prisma.venue.count()
  if (existingCount > 0) {
    console.log(`Found ${existingCount} existing venues, skipping seed`)
    return existingCount
  }

  // Sample venues data for Mannheim and Heidelberg
  const venues = [
    {
      name: "Skybar Mannheim",
      slug: "skybar-mannheim",
      category: "Nightlife",
      subcategory: "Rooftop Bar",
      city: "Mannheim",
      district: "Quadrate",
      address: "Q7 17-21, 68161 Mannheim",
      latitude: 49.4873,
      longitude: 8.466,
      phone: "+49 621 12345678",
      email: "info@skybar-mannheim.de",
      website: "https://www.skybar-mannheim.de",
      instagram: "skybar_mannheim",
      description:
        "Experience summer nights on our spectacular rooftop terrace with panoramic city views and craft cocktails.",
      shortDescription: "Rooftop bar with panoramic city views",
      priceRange: "€€",
      openingHours: JSON.stringify({
        monday: "18:00-01:00",
        tuesday: "18:00-01:00",
        wednesday: "18:00-01:00",
        thursday: "18:00-02:00",
        friday: "18:00-03:00",
        saturday: "18:00-03:00",
        sunday: "16:00-00:00",
      }),
      features: JSON.stringify(["Rooftop", "Cocktails", "City View", "DJ"]),
      amenities: JSON.stringify(["Outdoor Seating", "Reservations", "Card Payment"]),
      images: JSON.stringify([
        "/images/rooftop-bar.jpg",
        "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&h=600&fit=crop",
      ]),
      menuUrl: "https://www.skybar-mannheim.de/menu",
      reservationUrl: "https://www.skybar-mannheim.de/reservations",
      rating: 4.7,
      reviewCount: 128,
      checkInCount: 345,
      favoriteCount: 89,
      verified: true,
      featured: true,
    },
    {
      name: "MS Connexion",
      slug: "ms-connexion",
      category: "Music",
      subcategory: "Club",
      city: "Mannheim",
      district: "Jungbusch",
      address: "Angelstraße 33, 68199 Mannheim",
      latitude: 49.4913,
      longitude: 8.4553,
      phone: "+49 621 87654321",
      website: "https://www.msconnexion.de",
      instagram: "msconnexion",
      description: "Deep electronic beats in Mannheim's premier underground venue with state-of-the-art sound system.",
      shortDescription: "Premier electronic music venue",
      priceRange: "€€",
      openingHours: JSON.stringify({
        friday: "23:00-06:00",
        saturday: "23:00-08:00",
      }),
      features: JSON.stringify(["Live Music", "DJ Sets", "Dance Floor"]),
      amenities: JSON.stringify(["Bar", "Smoking Area", "Coat Check"]),
      images: JSON.stringify(["https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=600&fit=crop"]),
      rating: 4.5,
      reviewCount: 210,
      checkInCount: 780,
      favoriteCount: 156,
      verified: true,
    },
    {
      name: "Heidelberg Castle",
      slug: "heidelberg-castle",
      category: "Art",
      subcategory: "Historic Venue",
      city: "Heidelberg",
      address: "Schlosshof 1, 69117 Heidelberg",
      latitude: 49.4106,
      longitude: 8.7153,
      phone: "+49 6221 538431",
      website: "https://www.heidelberg-castle.de",
      description:
        "Historic castle hosting sophisticated evening with live jazz performances and premium wine selection.",
      shortDescription: "Historic castle with cultural events",
      priceRange: "€€€",
      openingHours: JSON.stringify({
        monday: "08:00-18:00",
        tuesday: "08:00-18:00",
        wednesday: "08:00-18:00",
        thursday: "08:00-18:00",
        friday: "08:00-18:00",
        saturday: "08:00-18:00",
        sunday: "08:00-18:00",
      }),
      features: JSON.stringify(["Historic Site", "Cultural Events", "Scenic Views"]),
      amenities: JSON.stringify(["Guided Tours", "Restaurant", "Gift Shop"]),
      images: JSON.stringify([
        "/images/jazz-castle.jpg",
        "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&h=600&fit=crop",
      ]),
      rating: 4.9,
      reviewCount: 342,
      checkInCount: 1245,
      favoriteCount: 278,
      verified: true,
      featured: true,
    },
    {
      name: "Alte Feuerwache",
      slug: "alte-feuerwache",
      category: "Culture",
      subcategory: "Event Space",
      city: "Mannheim",
      district: "Neckarstadt",
      address: "Brückenstraße 2, 68167 Mannheim",
      latitude: 49.5003,
      longitude: 8.4778,
      phone: "+49 621 1566055",
      email: "info@altefeuerwache.com",
      website: "https://www.altefeuerwache.com",
      description:
        "Celebrate local and international artists with exhibitions, performances, and interactive workshops.",
      shortDescription: "Cultural center in historic fire station",
      priceRange: "€€",
      openingHours: JSON.stringify({
        monday: "Closed",
        tuesday: "10:00-22:00",
        wednesday: "10:00-22:00",
        thursday: "10:00-22:00",
        friday: "10:00-00:00",
        saturday: "10:00-00:00",
        sunday: "12:00-20:00",
      }),
      features: JSON.stringify(["Live Performances", "Art Exhibitions", "Workshops"]),
      amenities: JSON.stringify(["Café", "Wheelchair Accessible", "Bike Parking"]),
      images: JSON.stringify(["https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&h=600&fit=crop"]),
      rating: 4.6,
      reviewCount: 187,
      checkInCount: 523,
      favoriteCount: 112,
      verified: true,
    },
    {
      name: "Luisenpark",
      slug: "luisenpark",
      category: "Social",
      subcategory: "Beer Garden",
      city: "Mannheim",
      address: "Theodor-Heuss-Anlage 2, 68165 Mannheim",
      latitude: 49.4786,
      longitude: 8.5008,
      phone: "+49 621 4100950",
      website: "https://www.luisenpark.de",
      description: "Relaxed afternoon concert in beautiful beer garden setting with local craft beers and live music.",
      shortDescription: "Beautiful park with beer garden",
      priceRange: "€",
      openingHours: JSON.stringify({
        monday: "09:00-21:00",
        tuesday: "09:00-21:00",
        wednesday: "09:00-21:00",
        thursday: "09:00-21:00",
        friday: "09:00-21:00",
        saturday: "09:00-21:00",
        sunday: "09:00-21:00",
      }),
      features: JSON.stringify(["Beer Garden", "Live Music", "Park", "Family Friendly"]),
      amenities: JSON.stringify(["Food Stalls", "Playground", "Boat Rental"]),
      images: JSON.stringify([
        "/images/beer-tasting.jpg",
        "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&h=600&fit=crop",
      ]),
      rating: 4.8,
      reviewCount: 412,
      checkInCount: 1876,
      favoriteCount: 324,
      verified: true,
    },
  ]

  // Insert venues
  const result = await prisma.venue.createMany({
    data: venues,
    skipDuplicates: true,
  })

  return result.count
}
